name: Update theme components

# Controls when the workflow will run
on:
  schedule:
    # Update theme automatically every month
    - cron: '0 0 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-theme-components:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SYNC_CONTENT }}
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Update theme components
        run: |
          hugo mod get -u
          hugo mod tidy
  
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_user_name: Cell[bot]
          commit_user_email: lrhx@users.noreply.github.com
          commit_message: ':arrow_up: Chore(theme): update components version'
